site_name: babylon
theme: readthedocs

nav:
    - Home: 'index.md'
    - Getting started: 'installation.md'
    - Concepts:
        - Contribute: 'contribute.md'
        - Environments: 'environment.md'
        - Library organization: 'organization.md'
    - References:
        - babylon: 'cli.md'
        - utils:
          - Environment: 'Utils/environment.md'
          - Decorators: 'Utils/decorators.md'

markdown_extensions:
    - mkdocs-click
plugins:
    - search
    - mkdocstrings