site_name: babylon
theme:
  name: material
  font:
    code: Fira Mono
  palette:
    scheme: slate
    primary: orange
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
  custom_dir: overrides
nav:
    - Home: 'index.md'
    - Getting started:
      - Installation: 'installation.md'
      - Dependencies: 'dependencies.md'
    - Concepts:
        - Contribute: 'contribute.md'
        - Environments: 'environment.md'
        - Plugins: 'plugins.md'
    - References:
        - babylon: 'cli.md'
        - classes:
            - Configuration: 'Utils/config.md'
            - Working Directory: 'Utils/working_dir.md'
        - functions:
            - Decorators: 'Utils/decorators.md'
            - Cosmotech Api: 'Utils/api.md'
            - Others: 'Utils/others.md'
        - plugins:
            - Dev-tools: 'plugins/devtools.md'

markdown_extensions:
    - attr_list
    - tables
    - mkdocs-click
    - pymdownx.snippets
plugins:
    - search
    - mkdocstrings
    - gen-files:
        scripts:
          - scripts/generate_dependencies_markdown.py
          - scripts/generate_index.py