site_name: babylon
theme:
  name: material
  palette:
    scheme: slate
    primary: orange
  features:
    - navigation.tabs
  custom_dir: overrides

nav:
    - Home: 'index.md'
    - Getting started:
      - Installation: 'installation.md'
      - Dependencies: 'dependencies.md'
    - Concepts:
        - Contribute: 'contribute.md'
        - Environments: 'environment.md'
        - Library organization: 'organization.md'
    - References:
        - babylon: 'cli.md'
        - utils:
          - Environment: 'Utils/environment.md'
          - Decorators: 'Utils/decorators.md'
          - Cosmotech Api: 'Utils/api.md'

markdown_extensions:
    - mkdocs-click
    - pymdownx.snippets
plugins:
    - search
    - mkdocstrings
    - gen-files:
        scripts:
          - scripts/generate_dependencies_markdown.py