site_name: babylon
theme:
  name: material
  font:
    code: Fira Mono
  logo: img/logo.png
  palette:
    scheme: slate
    primary: orange
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
  custom_dir: overrides
extra:
  version:
    provider: mike
nav:
    - Home: 'index.md'
    - Getting started:
      - Installation: 'installation.md'
      - Dependencies: 'dependencies.md'
    - Concepts:
        - Contribute: 'contribute.md'
        - Environments: 'environment.md'
        - Plugins: 'plugins.md'
        - Macro commands: 'macro.md'
        - Secrets management: 'Utils/secret_management.md'
    - References:
        - babylon: 'cli.md'
        - classes:
            - Configuration: 'Utils/config.md'
            - Working Directory: 'Utils/working_dir.md'
        - typing: 'Utils/typing.md'
        - functions:
            - Decorators: 'Utils/decorators.md'
            - Cosmotech Api: 'Utils/api.md'
            - Others: 'Utils/others.md'
        - plugins:
            - Dev-tools: 'plugins/devtools.md'

markdown_extensions:
    - mkdocs-click
    - admonition
    - attr_list
    - footnotes
    - md_in_html
    - tables
    - def_list
    - pymdownx.details
    - pymdownx.snippets
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
plugins:
    - search
    - mkdocstrings
    - gen-files:
        scripts:
          - scripts/generate_dependencies_markdown.py
          - scripts/generate_index.py
    - mike