site_name: babylon
repo_url: https://github.com/Cosmo-Tech/Babylon/home
repo_name: Cosmo-Tech/Babylon

theme:
  name: material
  font:
    code: Fira Mono
  logo: assets/img/logo.png
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - navigation.instant
    - navigation.footer
  custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
extra:
  version:
    provider: mike
nav:
  - Home: 'index.md'
  - Getting started:
    - Installation: 'getting_started/installation.md'
    - Dependencies: 'getting_started/dependencies.md'
  - Concepts:
      - Contribute: 'concepts/contribute.md'
      - Environments: 'concepts/environment.md'
      - Secrets management: 'concepts/secret_management.md'
  - References:
      - babylon: 'references/cli.md'
      - functions:
          - Decorators: 'references/decorators.md'

markdown_extensions:
  - mkdocs-click
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - tables
  - def_list
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      title: "In this page"
      permalink: true
plugins:
    - search
    - mkdocstrings
    - gen-files:
        scripts:
          - scripts/generate_index.py
          - scripts/generate_dependencies.py
    - mike