# SPDX-FileCopyrightText: Copyright (C) 2023-2026 Cosmo Tech
# SPDX-License-Identifier: LicenseRef-CosmoTech

sonar.projectKey=Babylon-main
sonar.projectName=Babylon (main)
sonar.tests=tests
sonar.python.version=3.12,3.13

