apiVersion: batch/v1
kind: Job
metadata:
  name: postgresql-init-${job_name}
  namespace: ${namespace}
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      containers:
        - name: postgresql-init
          image: postgres:17-trixie
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -e
              echo "INFO:  Starting schema initialization for ${workspace_schema}"

              SCHEMA_EXISTS=$(psql -h ${db_host} -p ${db_port} -U ${cosmotech_api_admin_username} -d ${cosmotech_api_database} \
                -tAc "SELECT 1 FROM information_schema.schemata WHERE schema_name = '${workspace_schema}'")

              if [ "$SCHEMA_EXISTS" = "1" ]; then
                echo "INFO:  Schema ${workspace_schema} already exists. Skipping creation."
              else
                psql -h ${db_host} -p ${db_port} -U ${cosmotech_api_admin_username} -d ${cosmotech_api_database} -c "CREATE SCHEMA ${workspace_schema} AUTHORIZATION ${cosmotech_api_writer_username};"
                echo "SUCCESS:  Schema created successfully"
              fi

              psql -h ${db_host} -p ${db_port} -U ${cosmotech_api_admin_username} -d ${cosmotech_api_database} -c "GRANT USAGE ON SCHEMA ${workspace_schema} TO ${cosmotech_api_reader_username};"
              echo "SUCCESS:  Permissions granted"
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgresql-cosmotechapi
                  key: admin-password
      restartPolicy: Never