name: check yapf formatting

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
jobs:
  check-formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Display Python version
        run: echo "##[set-output name=version;]$(python -c 'from Babylon.version import VERSION; print(VERSION)')"
      - name: run YAPF to test if python code is correctly formatted
        uses: AlexanderMelde/yapf-action@master
        with:
          args: --diff