name: linting flake8

on:
  push:
    branches:
      - "main"
      - "**-dev"
  pull_request:
    branches:
      - "main"
      - "**-dev"
jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: flake8 Lint Babylon
        uses: py-actions/flake8@v2
        with:
          max-line-length: "120"
          path: "Babylon"
      - name: flake8 Lint plugins/dev-tools
        uses: py-actions/flake8@v2
        with:
          max-line-length: "120"
          path: "plugins/dev_tools"