name: Test Api commands babylon with pytest 

env:
  BABYLON_SERVICE: ${{ vars.BABYLON_SERVICE }}
  BABYLON_TOKEN: ${{ secrets.BABYLON_TOKEN }}
  BABYLON_ORG_NAME: ${{ vars.BABYLON_ORG_NAME }}

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
      - "**-dev"
      - "feat**"
jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - uses: actions/checkout@v3
        name: Checkout repository
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v3
        with:
          python-version: "3.11"

      - name: install babylon and requirements
        run: |
          pip install -e .

      - name: run pytest
        run: |
          babylon namespace use -c test -p wa-adx-dev -s testid
          pytest . -v